#!/bin/bash -l

# Change working directory to user's home directory
cd "${HOME}"

# Start up Gnome desktop (only desktop we support so far)
"${ROOT}/desktops/${DESKTOP:-gnome}.sh"

# Kill vncserver when user logs out of desktop
vncserver -kill ${DISPLAY}
