version: 2
updates:
  # Bundler – root Gemfile (master)
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    
  # Bundler – apps/dashboard (master)
  - package-ecosystem: "bundler"
    directory: "/apps/dashboard"
    schedule:
      interval: "weekly"
    target-branch: "master"
    
  # npm – apps/dashboard (master)
  - package-ecosystem: "npm"
    directory: "/apps/dashboard"
    schedule:
      interval: "weekly"
    target-branch: "master"

  # npm - apps/shell (master)
  - package-ecosystem: "npm"
    directory: "/apps/shell"
    schedule:
      interval: "weekly"
    target-branch: "master"
  
  # Bundler - apps/myjobs (master)
  - package-ecosystem: "bundler"
    directory: "/apps/myjobs"
    schedule:
      interval: "weekly"
    target-branch: "master"
  
  # Bundler – root Gemfile (release_4.x)
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "release_4.*"

  # Bundler – apps/dashboard (release_4.x)
  - package-ecosystem: "bundler"
    directory: "/apps/dashboard"
    schedule:
      interval: "weekly"
    target-branch: "release_4.*"

  # npm – apps/dashboard (release_4.x)
  - package-ecosystem: "npm"
    directory: "/apps/dashboard"
    schedule:
      interval: "weekly"
    target-branch: "release_4.*"

  # npm - apps/shell (release_4.x)
  - package-ecosystem: "npm"
    directory: "/apps/shell"
    schedule:
      interval: "weekly"
    target-branch: "release_4.*"
    
  # Bundler - apps/myjobs (release_4.x)
  - package-ecosystem: "bundler"
    directory: "/apps/myjobs"
    schedule:
      interval: "weekly"
    target-branch: "release_4.*"
