component/activejobs:
  - changed-files:
    - any-glob-to-any-file: apps/activejobs/**/*

component/bc_desktop:
  - changed-files:
    - any-glob-to-any-file: apps/bc_desktop/**/*

component/dashboard:
  - changed-files:
    - any-glob-to-any-file: apps/dashboard/**/*

component/file_editor:
  - changed-files:
    - any-glob-to-any-file: apps/file-editor/**/*

component/file_browser:
  - changed-files:
    - any-glob-to-any-file: apps/files/**/*

component/jobcomposer:
  - changed-files:
    - any-glob-to-any-file: apps/myjobs/**/*

component/shell:
  - changed-files:
    - any-glob-to-any-file: apps/shell/**/*

component/nginx_stage:
  - changed-files:
    - any-glob-to-any-file: nginx_stage/**/*

component/mod_ood_proxy:
  - changed-files:
    - any-glob-to-any-file: mod_ood_proxy/**/*

component/ood_auth_map:
  - changed-files:
    - any-glob-to-any-file: ood_auth_map/**/*

component/ood_portal_generator:
  - changed-files:
    - any-glob-to-any-file: ood-portal-generator/**/*

area/build:
  - changed-files:
    - any-glob-to-any-file: lib/tasks/**/*
