image:
  file: .gitpod.Dockerfile

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    # Updates PR description to include Open in Gitpod button
    addBadge: true

tasks:
  - name: Bundle install and container startup
    init: |
      touch /tmp/.ood-lock
      bundle install
      rake dev:start
      rm /tmp/.ood-lock
      gp sync-done startup

  - name: Start dev container
    init: sleep 1 && while [ -f /tmp/.ood-lock ]; do sleep 1; done
    command: rake dev:exec
    openMode: split-left

ports:
  # Dex
  - port: 5556
    onOpen: ignore
    visibility: public

  # OnDemand
  - port: 8080
    onOpen: ignore
    visibility: public
