image:
  file: .gitpod.Dockerfile

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addCheck: true
    addBadge: true

tasks:
  - name: Start Development Container
    init: >
      rake docker:development &&
      gp sync-done start-dev-container
    command: rake docker:connect
    openMode: split-left

ports:
  # Rails web server
  - port: 8080
    onOpen: open-preview
  
  # Webpacker HMR server
  - port: 3035
    onOpen: ignore
