image:
  file: .gitpod.Dockerfile

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addCheck: true
    addBadge: true

tasks:
  - name: Rails
    init: >
      gem install bundler &&
      bin/bundle install &&
      bin/rails db:migrate &&
      bin/rails db:seed &&
      bin/yarn install --check-files &&
      gp sync-done bundle
    command: rails server
    openMode: split-left

  - name: Yarn
    init: >
      gp sync-await bundle
    command: bin/webpack-dev-server
    openMode: split-right

ports:
  # Rails web server
  - port: 3000
    onOpen: open-preview
  
  # Webpacker HMR server
  - port: 3035
    onOpen: ignore
