image:
  file: .gitpod.Dockerfile

workspaceLocation: "/ondemand"

tasks:
  - name: Boot
    init: >
      bundle install &&
      gp sync-done bundle

  - name: Start dev container
    init: gp sync-await bundle
    command: rake dev:start

  - name: Enter dev container
    command: rake dev:exec
    openMode: split-left

ports:
  # Dex
  - port: 5556
    onOpen: ignore
    visibility: public

  # OnDemand
  - port: 8080
    onOpen: open-browser
    visibility: public
