image:
  file: .gitpod.Dockerfile

tasks:
  - name: Bundle install
    init: >
      bundle install &&
      gp sync-done bundle

  - name: Start dev container
    init: >
      gp sync-await bundle
      rake dev:start
    command: rake dev:exec
    openMode: split-left

ports:
  # Dex
  - port: 5556
    onOpen: ignore
    visibility: public

  # OnDemand
  - port: 8080
    onOpen: open-browser
    visibility: public
