# style
Style/MultilineBlockChain:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: 'no_mixed_keys'
Style/ClassAndModuleChildren:
  EnforcedStyle: 'nested'
Style/WordArray:
  EnforcedStyle: 'brackets'
Style/SymbolArray:
  EnforcedStyle: 'brackets'

# layout
Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

# metrics
Metrics/ModuleLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Max: 20
  CountAsOne:
    - 'heredoc'
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 30

# rspec
RSpec/MultipleMemoizedHelpers:
  Max: 10
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MessageSpies:
  EnforcedStyle: receive
