# style
Style/MultilineBlockChain:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: 'no_mixed_keys'
Style/ClassAndModuleChildren:
  EnforcedStyle: 'nested'
Style/WordArray:
  EnforcedStyle: 'brackets'
Style/SymbolArray:
  EnforcedStyle: 'brackets'

# layout
Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table
