vars := $$OOD_IP $$OOD_SUBDOMAIN $$OOD_LUA_ROOT $$OOD_PUN_STAGE_CMD \
	$$OOD_USER_MAP_CMD $$OOD_PUN_SOCKET_ROOT $$OOD_PUBLIC_ROOT $$OOD_PUN_URI \
	$$OOD_NODE_URI $$OOD_NGINX_URI $$OOD_PUBLIC_URI

$(BUILDDIR)/$(CONFFILE): $(TMPLDIR)/$(CONFFILE).tmpl | $(BUILDDIR)
	$(RENDERER) '$(vars)' < $^ > $@

install: $(BUILDDIR)/$(CONFFILE)
	mkdir -p $(DESTDIR)$(PREFIX)
	cp $< $(DESTDIR)$(PREFIX)/$(CONFFILE)

$(BUILDDIR):
	mkdir -p $@

clean:
	rm $(BUILDDIR)/$(CONFFILE)
