FROM ood:latest

ARG USER=ood
ARG UID=1000
ARG GID=1000

RUN dnf reinstall -y httpd-tools && \
    dnf install -y \
        strace lua python3 && \
    dnf clean all && rm -rf /var/cache/dnf/*

RUN sed -i 's#^CREATE_MAIL_SPOOL=yes#CREATE_MAIL_SPOOL=no#' /etc/default/useradd; \
    grep $GID /etc/group >/dev/null || groupadd -g $GID $USER; \
    useradd -l -u $UID --create-home --gid $GID $USER && \
    echo "$USER ALL=(ALL) NOPASSWD:ALL" >/etc/sudoers.d/$USER

COPY docker/dev-entrypoint.sh /entrypoint.sh

CMD [ "/entrypoint.sh" ]
