# This is strictly an example Dockerfile for you to start with.
# OnDemand developers do not provide a container to be used in production,
# but you can use this example file to get started.

FROM rockylinux/rockylinux:9
LABEL maintainer="tdockendorf@osc.edu; johrstrom@osc.edu"


# setup the ondemand repositories
RUN dnf -y install https://yum.osc.edu/ondemand/4.0/ondemand-release-web-4.0-1.el9.noarch.rpm

# install all the dependencies
RUN dnf -y update && \
    dnf install -y dnf-utils epel-release && \
    dnf module enable -y ruby:3.3 nodejs:20 && \
    dnf install -y ondemand && \
    dnf clean all && rm -rf /var/cache/dnf/*

# this one bc centos:8 doesn't generate localhost cert
RUN /usr/libexec/httpd-ssl-gencerts

RUN systemctl enable httpd

EXPOSE 80
EXPOSE 443

CMD [ "/sbin/init" ]
