# Build
FROM rust:latest as builder
WORKDIR /app
COPY ood-proxy-rs/ .
RUN cargo build --release

# Runtime
FROM debian:buster-slim as runtime
WORKDIR /app
RUN apt-get update -y \
    && apt-get install -y --no-install-recommends openssl \
    # Clean up
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/target/release/ood-proxy-rs ood-proxy-rs
ENTRYPOINT ["./ood-proxy-rs"]
