###########################
# Build options
###########################

PREFIX   := /opt/rh/httpd24/root/etc/httpd/conf.d
TMPLDIR  := templates
BUILDDIR := build
CONFFILE := ood-portal.conf
RENDERER := envsubst

###########################
# Server specific options
###########################

# IP used for Open OnDemand portal
OOD_IP := *:7000

# Subdomain used for the Open OnDemand portal
OOD_SUBDOMAIN := apps.ondemand.org

# Type of user authentication used for Open OnDemand portal
OOD_AUTH_TYPE := openid-connect

###########################
# System specific options
###########################

# Path to the Open OnDemand Lua scripts
OOD_LUA_ROOT := /nfs/17/jnicklas/Development/mod_ood_proxy/lib

# Command used to stage PUNs
OOD_PUN_STAGE_CMD := sudo /opt/ood/nginx_stage/sbin/nginx_stage_dev --config /nfs/17/jnicklas/Development/nginx_stage/config.yml --

# Command used to map users to system level users
OOD_USER_MAP_CMD := /nfs/17/jnicklas/Development/osc-user-map/bin/osc-user-map

# Path to the root location of PUN socket files
OOD_PUN_SOCKET_ROOT := /var/tmp/nginx_stage0/var/run/nginx

# Path to publicly available assets
OOD_PUBLIC_ROOT := /nfs/gpfs/PZS0645/www/public

###########################
# OOD Portal URIs
###########################

# Reverse proxy to backend PUNs
OOD_PUN_URI := /pun

# Reverse proxy to backend nodes
OOD_NODE_URI := /node

# Control the backend PUN (e.g., start, stop, reload, ...)
OOD_NGINX_URI := /nginx

# Serve up publicly available assets
OOD_PUBLIC_URI := /public


###########################
# Do not modify below
###########################

include targets.mk
