source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '6.1.7.3'
# Use sqlite3 as the database for Active Record
# Note that the version has been fixed due to an incompatibilty
# https://github.com/rails/rails/issues/35153
gem 'sqlite3', '1.4.2'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
# gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', group: :doc, require: false

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem 'rails-controller-testing'
  gem 'mocha', '~> 1.1'
  gem 'climate_control', '~> 0.2'
  gem 'timecop', '~> 0.9'
end


group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  # gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  # gem 'spring'
end

gem "autoprefixer-rails", "~> 8.4"
gem "bootstrap-sass", "~> 3.4.1"
gem "bootstrap_form", "~> 2.7.0"
gem 'font-awesome-sass', '~> 5.0'
gem "local_time", "~> 1.0.3"
gem 'dotenv-rails', '~> 2.1'
gem 'jquery-datatables-rails', '~> 3.4'
gem "js-routes", "~> 1.2.4"
gem 'osc_machete_rails', '~> 2.1.2'
gem 'pbs', '~> 2.2.1'
gem 'ood_appkit', '~> 2.0'

# we have to lock rdoc because 6.4 depends on psych 4.0 which breaks with
# Psych::BadAlias: Cannot load database configuration: Unknown alias: default
gem 'rdoc', '6.3.3'

# addressable 2.8.2 has this bug:  https://github.com/sporkmonger/addressable/issues/498
gem 'addressable', '2.8.1'
