
export function accessEventsData() {
  return [
    {
      "id": "8206",
      "description": "<strong>Enhance Your Skills with Expert Guidance&nbsp;</strong>Join our informative Office Hours via Zoom to learn more about Sage. Whether you're new to Sage or an experienced user, our sessions can help you:<ul><li><strong>Navigate the Portal:</strong> Get comfortable with Sage's features.</li><li><strong>Request an Allocation at Sage:</strong> Get help with requesting resources and allocations on Sage.</li><li><strong>Build and Run AI Edge Applications:</strong> Develop and manage your AI applications.</li><li><strong>Ask Questions &amp; Get Unblocked:</strong> Receive assistance with any challenges you encounter.</li></ul><strong>Weekly Sessions:</strong><ul><li>Tuesdays: 11:00 AM - 12:00 PM CST</li><li>Thursdays: 3:00 PM - 4:00 PM CST</li></ul>To receive a Zoom link for a session, please make sure to <strong>register </strong><a href=\"https://docs.google.com/forms/d/e/1FAIpQLScHPrkWFr_CVTN2EQ9W0dXSlHtQ2JD6gs7P1Sf_MnQYApjgGA/viewform?usp=header\"><strong>here</strong></a>.If neither of these times work, please include your availability in the registration form and we will be happy to find a time that works for you. As always, please <a href=\"https://sagecontinuum.org/docs/contact-us\">Contact Us</a> if you have any questions. We look forward to hearing from you!",
      "contact": "support@waggle-edge.ai",
      "event_affiliation": "Community, nairr_pilot",
      "created": "2025-07-28T20:29:31Z",
      "changed": "2025-07-28T22:20:39Z",
      "event_type": "Office Hours",
      "location": "Virtual",
      "registration": "https://sagecontinuum.org/docs/events/office-hours",
      "skill_level": "Beginner, Intermediate, Advanced",
      "custom_event_tags": "ai, machine-learning, edge-computing, sensors, distributed-computing, gpu",
      "title": "Sage Office Hours",
      "field_video": "",
      "date": "2026-04-14T12:00:00Z",
      "date_1": "2026-04-14T13:00:00Z",
      "speakers": ""
    },
    {
      "id": "8142",
      "description": "<strong>Enhance Your Skills with Expert Guidance&nbsp;</strong>Join our informative Office Hours via Zoom to learn more about Sage. Whether you're new to Sage or an experienced user, our sessions can help you:<ul><li><strong>Navigate the Portal:</strong> Get comfortable with Sage's features.</li><li><strong>Request an Allocation at Sage:</strong> Get help with requesting resources and allocations on Sage.</li><li><strong>Build and Run AI Edge Applications:</strong> Develop and manage your AI applications.</li><li><strong>Ask Questions &amp; Get Unblocked:</strong> Receive assistance with any challenges you encounter.</li></ul><strong>Weekly Sessions:</strong><ul><li>Tuesdays: 11:00 AM - 12:00 PM CST</li><li>Thursdays: 3:00 PM - 4:00 PM CST</li></ul>To receive a Zoom link for a session, please make sure to <strong>register </strong><a href=\"https://docs.google.com/forms/d/e/1FAIpQLScHPrkWFr_CVTN2EQ9W0dXSlHtQ2JD6gs7P1Sf_MnQYApjgGA/viewform?usp=header\"><strong>here</strong></a>.If neither of these times work, please include your availability in the registration form and we will be happy to find a time that works for you. As always, please <a href=\"https://sagecontinuum.org/docs/contact-us\">Contact Us</a> if you have any questions. We look forward to hearing from you!",
      "contact": "support@waggle-edge.ai",
      "event_affiliation": "Community, nairr_pilot",
      "created": "2025-07-24T22:18:56Z",
      "changed": "2025-07-28T22:16:54Z",
      "event_type": "Office Hours",
      "location": "Virtual",
      "registration": "https://sagecontinuum.org/docs/events/office-hours",
      "skill_level": "Beginner, Intermediate, Advanced",
      "custom_event_tags": "ai, machine-learning, edge-computing, sensors, distributed-computing, gpu",
      "title": "Sage Office Hours",
      "field_video": "",
      "date": "2026-04-16T16:00:00Z",
      "date_1": "2026-04-16T17:00:00Z",
      "speakers": ""
    },
    {
      "id": "8207",
      "description": "<strong>Enhance Your Skills with Expert Guidance&nbsp;</strong>Join our informative Office Hours via Zoom to learn more about Sage. Whether you're new to Sage or an experienced user, our sessions can help you:<ul><li><strong>Navigate the Portal:</strong> Get comfortable with Sage's features.</li><li><strong>Request an Allocation at Sage:</strong> Get help with requesting resources and allocations on Sage.</li><li><strong>Build and Run AI Edge Applications:</strong> Develop and manage your AI applications.</li><li><strong>Ask Questions &amp; Get Unblocked:</strong> Receive assistance with any challenges you encounter.</li></ul><strong>Weekly Sessions:</strong><ul><li>Tuesdays: 11:00 AM - 12:00 PM CST</li><li>Thursdays: 3:00 PM - 4:00 PM CST</li></ul>To receive a Zoom link for a session, please make sure to <strong>register </strong><a href=\"https://docs.google.com/forms/d/e/1FAIpQLScHPrkWFr_CVTN2EQ9W0dXSlHtQ2JD6gs7P1Sf_MnQYApjgGA/viewform?usp=header\"><strong>here</strong></a>.If neither of these times work, please include your availability in the registration form and we will be happy to find a time that works for you. As always, please <a href=\"https://sagecontinuum.org/docs/contact-us\">Contact Us</a> if you have any questions. We look forward to hearing from you!",
      "contact": "support@waggle-edge.ai",
      "event_affiliation": "Community, nairr_pilot",
      "created": "2025-07-28T20:29:31Z",
      "changed": "2025-07-28T22:20:39Z",
      "event_type": "Office Hours",
      "location": "Virtual",
      "registration": "https://sagecontinuum.org/docs/events/office-hours",
      "skill_level": "Beginner, Intermediate, Advanced",
      "custom_event_tags": "ai, machine-learning, edge-computing, sensors, distributed-computing, gpu",
      "title": "Sage Office Hours",
      "field_video": "",
      "date": "2026-04-21T12:00:00Z",
      "date_1": "2026-04-21T13:00:00Z",
      "speakers": ""
    },
    {
      "id": "8143",
      "description": "<strong>Enhance Your Skills with Expert Guidance&nbsp;</strong>Join our informative Office Hours via Zoom to learn more about Sage. Whether you're new to Sage or an experienced user, our sessions can help you:<ul><li><strong>Navigate the Portal:</strong> Get comfortable with Sage's features.</li><li><strong>Request an Allocation at Sage:</strong> Get help with requesting resources and allocations on Sage.</li><li><strong>Build and Run AI Edge Applications:</strong> Develop and manage your AI applications.</li><li><strong>Ask Questions &amp; Get Unblocked:</strong> Receive assistance with any challenges you encounter.</li></ul><strong>Weekly Sessions:</strong><ul><li>Tuesdays: 11:00 AM - 12:00 PM CST</li><li>Thursdays: 3:00 PM - 4:00 PM CST</li></ul>To receive a Zoom link for a session, please make sure to <strong>register </strong><a href=\"https://docs.google.com/forms/d/e/1FAIpQLScHPrkWFr_CVTN2EQ9W0dXSlHtQ2JD6gs7P1Sf_MnQYApjgGA/viewform?usp=header\"><strong>here</strong></a>.If neither of these times work, please include your availability in the registration form and we will be happy to find a time that works for you. As always, please <a href=\"https://sagecontinuum.org/docs/contact-us\">Contact Us</a> if you have any questions. We look forward to hearing from you!",
      "contact": "support@waggle-edge.ai",
      "event_affiliation": "Community, nairr_pilot",
      "created": "2025-07-24T22:18:56Z",
      "changed": "2025-07-28T22:16:54Z",
      "event_type": "Office Hours",
      "location": "Virtual",
      "registration": "https://sagecontinuum.org/docs/events/office-hours",
      "skill_level": "Beginner, Intermediate, Advanced",
      "custom_event_tags": "ai, machine-learning, edge-computing, sensors, distributed-computing, gpu",
      "title": "Sage Office Hours",
      "field_video": "",
      "date": "2026-04-23T16:00:00Z",
      "date_1": "2026-04-23T17:00:00Z",
      "speakers": ""
    },
    {
      "id": "8208",
      "description": "<strong>Enhance Your Skills with Expert Guidance&nbsp;</strong>Join our informative Office Hours via Zoom to learn more about Sage. Whether you're new to Sage or an experienced user, our sessions can help you:<ul><li><strong>Navigate the Portal:</strong> Get comfortable with Sage's features.</li><li><strong>Request an Allocation at Sage:</strong> Get help with requesting resources and allocations on Sage.</li><li><strong>Build and Run AI Edge Applications:</strong> Develop and manage your AI applications.</li><li><strong>Ask Questions &amp; Get Unblocked:</strong> Receive assistance with any challenges you encounter.</li></ul><strong>Weekly Sessions:</strong><ul><li>Tuesdays: 11:00 AM - 12:00 PM CST</li><li>Thursdays: 3:00 PM - 4:00 PM CST</li></ul>To receive a Zoom link for a session, please make sure to <strong>register </strong><a href=\"https://docs.google.com/forms/d/e/1FAIpQLScHPrkWFr_CVTN2EQ9W0dXSlHtQ2JD6gs7P1Sf_MnQYApjgGA/viewform?usp=header\"><strong>here</strong></a>.If neither of these times work, please include your availability in the registration form and we will be happy to find a time that works for you. As always, please <a href=\"https://sagecontinuum.org/docs/contact-us\">Contact Us</a> if you have any questions. We look forward to hearing from you!",
      "contact": "support@waggle-edge.ai",
      "event_affiliation": "Community, nairr_pilot",
      "created": "2025-07-28T20:29:31Z",
      "changed": "2025-07-28T22:20:39Z",
      "event_type": "Office Hours",
      "location": "Virtual",
      "registration": "https://sagecontinuum.org/docs/events/office-hours",
      "skill_level": "Beginner, Intermediate, Advanced",
      "custom_event_tags": "ai, machine-learning, edge-computing, sensors, distributed-computing, gpu",
      "title": "Sage Office Hours",
      "field_video": "",
      "date": "2026-04-28T12:00:00Z",
      "date_1": "2026-04-28T13:00:00Z",
      "speakers": ""
    },
    {
      "id": "8144",
      "description": "<strong>Enhance Your Skills with Expert Guidance&nbsp;</strong>Join our informative Office Hours via Zoom to learn more about Sage. Whether you're new to Sage or an experienced user, our sessions can help you:<ul><li><strong>Navigate the Portal:</strong> Get comfortable with Sage's features.</li><li><strong>Request an Allocation at Sage:</strong> Get help with requesting resources and allocations on Sage.</li><li><strong>Build and Run AI Edge Applications:</strong> Develop and manage your AI applications.</li><li><strong>Ask Questions &amp; Get Unblocked:</strong> Receive assistance with any challenges you encounter.</li></ul><strong>Weekly Sessions:</strong><ul><li>Tuesdays: 11:00 AM - 12:00 PM CST</li><li>Thursdays: 3:00 PM - 4:00 PM CST</li></ul>To receive a Zoom link for a session, please make sure to <strong>register </strong><a href=\"https://docs.google.com/forms/d/e/1FAIpQLScHPrkWFr_CVTN2EQ9W0dXSlHtQ2JD6gs7P1Sf_MnQYApjgGA/viewform?usp=header\"><strong>here</strong></a>.If neither of these times work, please include your availability in the registration form and we will be happy to find a time that works for you. As always, please <a href=\"https://sagecontinuum.org/docs/contact-us\">Contact Us</a> if you have any questions. We look forward to hearing from you!",
      "contact": "support@waggle-edge.ai",
      "event_affiliation": "Community, nairr_pilot",
      "created": "2025-07-24T22:18:56Z",
      "changed": "2025-07-28T22:16:54Z",
      "event_type": "Office Hours",
      "location": "Virtual",
      "registration": "https://sagecontinuum.org/docs/events/office-hours",
      "skill_level": "Beginner, Intermediate, Advanced",
      "custom_event_tags": "ai, machine-learning, edge-computing, sensors, distributed-computing, gpu",
      "title": "Sage Office Hours",
      "field_video": "",
      "date": "2026-04-30T16:00:00Z",
      "date_1": "2026-04-30T17:00:00Z",
      "speakers": ""
    },
    {
      "id": "8209",
      "description": "<strong>Enhance Your Skills with Expert Guidance&nbsp;</strong>Join our informative Office Hours via Zoom to learn more about Sage. Whether you're new to Sage or an experienced user, our sessions can help you:<ul><li><strong>Navigate the Portal:</strong> Get comfortable with Sage's features.</li><li><strong>Request an Allocation at Sage:</strong> Get help with requesting resources and allocations on Sage.</li><li><strong>Build and Run AI Edge Applications:</strong> Develop and manage your AI applications.</li><li><strong>Ask Questions &amp; Get Unblocked:</strong> Receive assistance with any challenges you encounter.</li></ul><strong>Weekly Sessions:</strong><ul><li>Tuesdays: 11:00 AM - 12:00 PM CST</li><li>Thursdays: 3:00 PM - 4:00 PM CST</li></ul>To receive a Zoom link for a session, please make sure to <strong>register </strong><a href=\"https://docs.google.com/forms/d/e/1FAIpQLScHPrkWFr_CVTN2EQ9W0dXSlHtQ2JD6gs7P1Sf_MnQYApjgGA/viewform?usp=header\"><strong>here</strong></a>.If neither of these times work, please include your availability in the registration form and we will be happy to find a time that works for you. As always, please <a href=\"https://sagecontinuum.org/docs/contact-us\">Contact Us</a> if you have any questions. We look forward to hearing from you!",
      "contact": "support@waggle-edge.ai",
      "event_affiliation": "Community, nairr_pilot",
      "created": "2025-07-28T20:29:31Z",
      "changed": "2025-07-28T22:20:39Z",
      "event_type": "Office Hours",
      "location": "Virtual",
      "registration": "https://sagecontinuum.org/docs/events/office-hours",
      "skill_level": "Beginner, Intermediate, Advanced",
      "custom_event_tags": "ai, machine-learning, edge-computing, sensors, distributed-computing, gpu",
      "title": "Sage Office Hours",
      "field_video": "",
      "date": "2026-05-05T12:00:00Z",
      "date_1": "2026-05-05T13:00:00Z",
      "speakers": ""
    },
    {
      "id": "8501",
      "description": "Join our monthly community-hosted call<em>&nbsp;</em>to learn practical tips for using this powerful, web-based platform that gives you seamless access to HPC resources—no software needed.Happening the first Thursday of every month at 1 PM EDT, these sessions are ideal for both new and experienced users looking to streamline workflows and enhance research productivity.Register using the registration link to receive the Zoom details. Recordings of past sessions are available on the <a href=\"https://openondemand.org/resources#video-archive\">Open OnDemand website</a>.&nbsp;",
      "contact": "",
      "event_affiliation": "ACCESS Collaboration, nairr_pilot",
      "created": "2025-09-15T14:39:34Z",
      "changed": "2025-09-15T14:40:14Z",
      "event_type": "other",
      "location": "Zoom",
      "registration": "https://utah.zoom.us/meeting/register/tJYqfuqqrToqGtMMel3jTB6OGpi1hUWtFdmJ#/registration",
      "skill_level": "",
      "custom_event_tags": "open-ondemand",
      "title": "Open OnDemand Tips and Tricks Call",
      "field_video": "",
      "date": "2026-05-07T13:00:00Z",
      "date_1": "2026-05-07T14:00:00Z",
      "speakers": ""
    },
    {
      "id": "8145",
      "description": "<strong>Enhance Your Skills with Expert Guidance&nbsp;</strong>Join our informative Office Hours via Zoom to learn more about Sage. Whether you're new to Sage or an experienced user, our sessions can help you:<ul><li><strong>Navigate the Portal:</strong> Get comfortable with Sage's features.</li><li><strong>Request an Allocation at Sage:</strong> Get help with requesting resources and allocations on Sage.</li><li><strong>Build and Run AI Edge Applications:</strong> Develop and manage your AI applications.</li><li><strong>Ask Questions &amp; Get Unblocked:</strong> Receive assistance with any challenges you encounter.</li></ul><strong>Weekly Sessions:</strong><ul><li>Tuesdays: 11:00 AM - 12:00 PM CST</li><li>Thursdays: 3:00 PM - 4:00 PM CST</li></ul>To receive a Zoom link for a session, please make sure to <strong>register </strong><a href=\"https://docs.google.com/forms/d/e/1FAIpQLScHPrkWFr_CVTN2EQ9W0dXSlHtQ2JD6gs7P1Sf_MnQYApjgGA/viewform?usp=header\"><strong>here</strong></a>.If neither of these times work, please include your availability in the registration form and we will be happy to find a time that works for you. As always, please <a href=\"https://sagecontinuum.org/docs/contact-us\">Contact Us</a> if you have any questions. We look forward to hearing from you!",
      "contact": "support@waggle-edge.ai",
      "event_affiliation": "Community, nairr_pilot",
      "created": "2025-07-24T22:18:56Z",
      "changed": "2025-07-28T22:16:54Z",
      "event_type": "Office Hours",
      "location": "Virtual",
      "registration": "https://sagecontinuum.org/docs/events/office-hours",
      "skill_level": "Beginner, Intermediate, Advanced",
      "custom_event_tags": "ai, machine-learning, edge-computing, sensors, distributed-computing, gpu",
      "title": "Sage Office Hours",
      "field_video": "",
      "date": "2026-05-07T16:00:00Z",
      "date_1": "2026-05-07T17:00:00Z",
      "speakers": ""
    },
    {
      "id": "8210",
      "description": "<strong>Enhance Your Skills with Expert Guidance&nbsp;</strong>Join our informative Office Hours via Zoom to learn more about Sage. Whether you're new to Sage or an experienced user, our sessions can help you:<ul><li><strong>Navigate the Portal:</strong> Get comfortable with Sage's features.</li><li><strong>Request an Allocation at Sage:</strong> Get help with requesting resources and allocations on Sage.</li><li><strong>Build and Run AI Edge Applications:</strong> Develop and manage your AI applications.</li><li><strong>Ask Questions &amp; Get Unblocked:</strong> Receive assistance with any challenges you encounter.</li></ul><strong>Weekly Sessions:</strong><ul><li>Tuesdays: 11:00 AM - 12:00 PM CST</li><li>Thursdays: 3:00 PM - 4:00 PM CST</li></ul>To receive a Zoom link for a session, please make sure to <strong>register </strong><a href=\"https://docs.google.com/forms/d/e/1FAIpQLScHPrkWFr_CVTN2EQ9W0dXSlHtQ2JD6gs7P1Sf_MnQYApjgGA/viewform?usp=header\"><strong>here</strong></a>.If neither of these times work, please include your availability in the registration form and we will be happy to find a time that works for you. As always, please <a href=\"https://sagecontinuum.org/docs/contact-us\">Contact Us</a> if you have any questions. We look forward to hearing from you!",
      "contact": "support@waggle-edge.ai",
      "event_affiliation": "Community, nairr_pilot",
      "created": "2025-07-28T20:29:31Z",
      "changed": "2025-07-28T22:20:39Z",
      "event_type": "Office Hours",
      "location": "Virtual",
      "registration": "https://sagecontinuum.org/docs/events/office-hours",
      "skill_level": "Beginner, Intermediate, Advanced",
      "custom_event_tags": "ai, machine-learning, edge-computing, sensors, distributed-computing, gpu",
      "title": "Sage Office Hours",
      "field_video": "",
      "date": "2026-05-12T12:00:00Z",
      "date_1": "2026-05-12T13:00:00Z",
      "speakers": ""
    },
    {
      "id": "8146",
      "description": "<strong>Enhance Your Skills with Expert Guidance&nbsp;</strong>Join our informative Office Hours via Zoom to learn more about Sage. Whether you're new to Sage or an experienced user, our sessions can help you:<ul><li><strong>Navigate the Portal:</strong> Get comfortable with Sage's features.</li><li><strong>Request an Allocation at Sage:</strong> Get help with requesting resources and allocations on Sage.</li><li><strong>Build and Run AI Edge Applications:</strong> Develop and manage your AI applications.</li><li><strong>Ask Questions &amp; Get Unblocked:</strong> Receive assistance with any challenges you encounter.</li></ul><strong>Weekly Sessions:</strong><ul><li>Tuesdays: 11:00 AM - 12:00 PM CST</li><li>Thursdays: 3:00 PM - 4:00 PM CST</li></ul>To receive a Zoom link for a session, please make sure to <strong>register </strong><a href=\"https://docs.google.com/forms/d/e/1FAIpQLScHPrkWFr_CVTN2EQ9W0dXSlHtQ2JD6gs7P1Sf_MnQYApjgGA/viewform?usp=header\"><strong>here</strong></a>.If neither of these times work, please include your availability in the registration form and we will be happy to find a time that works for you. As always, please <a href=\"https://sagecontinuum.org/docs/contact-us\">Contact Us</a> if you have any questions. We look forward to hearing from you!",
      "contact": "support@waggle-edge.ai",
      "event_affiliation": "Community, nairr_pilot",
      "created": "2025-07-24T22:18:56Z",
      "changed": "2025-07-28T22:16:54Z",
      "event_type": "Office Hours",
      "location": "Virtual",
      "registration": "https://sagecontinuum.org/docs/events/office-hours",
      "skill_level": "Beginner, Intermediate, Advanced",
      "custom_event_tags": "ai, machine-learning, edge-computing, sensors, distributed-computing, gpu",
      "title": "Sage Office Hours",
      "field_video": "",
      "date": "2026-05-14T16:00:00Z",
      "date_1": "2026-05-14T17:00:00Z",
      "speakers": ""
    },
    {
      "id": "8211",
      "description": "<strong>Enhance Your Skills with Expert Guidance&nbsp;</strong>Join our informative Office Hours via Zoom to learn more about Sage. Whether you're new to Sage or an experienced user, our sessions can help you:<ul><li><strong>Navigate the Portal:</strong> Get comfortable with Sage's features.</li><li><strong>Request an Allocation at Sage:</strong> Get help with requesting resources and allocations on Sage.</li><li><strong>Build and Run AI Edge Applications:</strong> Develop and manage your AI applications.</li><li><strong>Ask Questions &amp; Get Unblocked:</strong> Receive assistance with any challenges you encounter.</li></ul><strong>Weekly Sessions:</strong><ul><li>Tuesdays: 11:00 AM - 12:00 PM CST</li><li>Thursdays: 3:00 PM - 4:00 PM CST</li></ul>To receive a Zoom link for a session, please make sure to <strong>register </strong><a href=\"https://docs.google.com/forms/d/e/1FAIpQLScHPrkWFr_CVTN2EQ9W0dXSlHtQ2JD6gs7P1Sf_MnQYApjgGA/viewform?usp=header\"><strong>here</strong></a>.If neither of these times work, please include your availability in the registration form and we will be happy to find a time that works for you. As always, please <a href=\"https://sagecontinuum.org/docs/contact-us\">Contact Us</a> if you have any questions. We look forward to hearing from you!",
      "contact": "support@waggle-edge.ai",
      "event_affiliation": "Community, nairr_pilot",
      "created": "2025-07-28T20:29:31Z",
      "changed": "2025-07-28T22:20:39Z",
      "event_type": "Office Hours",
      "location": "Virtual",
      "registration": "https://sagecontinuum.org/docs/events/office-hours",
      "skill_level": "Beginner, Intermediate, Advanced",
      "custom_event_tags": "ai, machine-learning, edge-computing, sensors, distributed-computing, gpu",
      "title": "Sage Office Hours",
      "field_video": "",
      "date": "2026-05-19T12:00:00Z",
      "date_1": "2026-05-19T13:00:00Z",
      "speakers": ""
    },
    {
      "id": "8147",
      "description": "<strong>Enhance Your Skills with Expert Guidance&nbsp;</strong>Join our informative Office Hours via Zoom to learn more about Sage. Whether you're new to Sage or an experienced user, our sessions can help you:<ul><li><strong>Navigate the Portal:</strong> Get comfortable with Sage's features.</li><li><strong>Request an Allocation at Sage:</strong> Get help with requesting resources and allocations on Sage.</li><li><strong>Build and Run AI Edge Applications:</strong> Develop and manage your AI applications.</li><li><strong>Ask Questions &amp; Get Unblocked:</strong> Receive assistance with any challenges you encounter.</li></ul><strong>Weekly Sessions:</strong><ul><li>Tuesdays: 11:00 AM - 12:00 PM CST</li><li>Thursdays: 3:00 PM - 4:00 PM CST</li></ul>To receive a Zoom link for a session, please make sure to <strong>register </strong><a href=\"https://docs.google.com/forms/d/e/1FAIpQLScHPrkWFr_CVTN2EQ9W0dXSlHtQ2JD6gs7P1Sf_MnQYApjgGA/viewform?usp=header\"><strong>here</strong></a>.If neither of these times work, please include your availability in the registration form and we will be happy to find a time that works for you. As always, please <a href=\"https://sagecontinuum.org/docs/contact-us\">Contact Us</a> if you have any questions. We look forward to hearing from you!",
      "contact": "support@waggle-edge.ai",
      "event_affiliation": "Community, nairr_pilot",
      "created": "2025-07-24T22:18:56Z",
      "changed": "2025-07-28T22:16:54Z",
      "event_type": "Office Hours",
      "location": "Virtual",
      "registration": "https://sagecontinuum.org/docs/events/office-hours",
      "skill_level": "Beginner, Intermediate, Advanced",
      "custom_event_tags": "ai, machine-learning, edge-computing, sensors, distributed-computing, gpu",
      "title": "Sage Office Hours",
      "field_video": "",
      "date": "2026-05-21T16:00:00Z",
      "date_1": "2026-05-21T17:00:00Z",
      "speakers": ""
    },
    {
      "id": "8212",
      "description": "<strong>Enhance Your Skills with Expert Guidance&nbsp;</strong>Join our informative Office Hours via Zoom to learn more about Sage. Whether you're new to Sage or an experienced user, our sessions can help you:<ul><li><strong>Navigate the Portal:</strong> Get comfortable with Sage's features.</li><li><strong>Request an Allocation at Sage:</strong> Get help with requesting resources and allocations on Sage.</li><li><strong>Build and Run AI Edge Applications:</strong> Develop and manage your AI applications.</li><li><strong>Ask Questions &amp; Get Unblocked:</strong> Receive assistance with any challenges you encounter.</li></ul><strong>Weekly Sessions:</strong><ul><li>Tuesdays: 11:00 AM - 12:00 PM CST</li><li>Thursdays: 3:00 PM - 4:00 PM CST</li></ul>To receive a Zoom link for a session, please make sure to <strong>register </strong><a href=\"https://docs.google.com/forms/d/e/1FAIpQLScHPrkWFr_CVTN2EQ9W0dXSlHtQ2JD6gs7P1Sf_MnQYApjgGA/viewform?usp=header\"><strong>here</strong></a>.If neither of these times work, please include your availability in the registration form and we will be happy to find a time that works for you. As always, please <a href=\"https://sagecontinuum.org/docs/contact-us\">Contact Us</a> if you have any questions. We look forward to hearing from you!",
      "contact": "support@waggle-edge.ai",
      "event_affiliation": "Community, nairr_pilot",
      "created": "2025-07-28T20:29:31Z",
      "changed": "2025-07-28T22:20:39Z",
      "event_type": "Office Hours",
      "location": "Virtual",
      "registration": "https://sagecontinuum.org/docs/events/office-hours",
      "skill_level": "Beginner, Intermediate, Advanced",
      "custom_event_tags": "ai, machine-learning, edge-computing, sensors, distributed-computing, gpu",
      "title": "Sage Office Hours",
      "field_video": "",
      "date": "2026-05-26T12:00:00Z",
      "date_1": "2026-05-26T13:00:00Z",
      "speakers": ""
    },
    {
      "id": "8148",
      "description": "<strong>Enhance Your Skills with Expert Guidance&nbsp;</strong>Join our informative Office Hours via Zoom to learn more about Sage. Whether you're new to Sage or an experienced user, our sessions can help you:<ul><li><strong>Navigate the Portal:</strong> Get comfortable with Sage's features.</li><li><strong>Request an Allocation at Sage:</strong> Get help with requesting resources and allocations on Sage.</li><li><strong>Build and Run AI Edge Applications:</strong> Develop and manage your AI applications.</li><li><strong>Ask Questions &amp; Get Unblocked:</strong> Receive assistance with any challenges you encounter.</li></ul><strong>Weekly Sessions:</strong><ul><li>Tuesdays: 11:00 AM - 12:00 PM CST</li><li>Thursdays: 3:00 PM - 4:00 PM CST</li></ul>To receive a Zoom link for a session, please make sure to <strong>register </strong><a href=\"https://docs.google.com/forms/d/e/1FAIpQLScHPrkWFr_CVTN2EQ9W0dXSlHtQ2JD6gs7P1Sf_MnQYApjgGA/viewform?usp=header\"><strong>here</strong></a>.If neither of these times work, please include your availability in the registration form and we will be happy to find a time that works for you. As always, please <a href=\"https://sagecontinuum.org/docs/contact-us\">Contact Us</a> if you have any questions. We look forward to hearing from you!",
      "contact": "support@waggle-edge.ai",
      "event_affiliation": "Community, nairr_pilot",
      "created": "2025-07-24T22:18:56Z",
      "changed": "2025-07-28T22:16:54Z",
      "event_type": "Office Hours",
      "location": "Virtual",
      "registration": "https://sagecontinuum.org/docs/events/office-hours",
      "skill_level": "Beginner, Intermediate, Advanced",
      "custom_event_tags": "ai, machine-learning, edge-computing, sensors, distributed-computing, gpu",
      "title": "Sage Office Hours",
      "field_video": "",
      "date": "2026-05-28T16:00:00Z",
      "date_1": "2026-05-28T17:00:00Z",
      "speakers": ""
    },
    {
      "id": "8213",
      "description": "<strong>Enhance Your Skills with Expert Guidance&nbsp;</strong>Join our informative Office Hours via Zoom to learn more about Sage. Whether you're new to Sage or an experienced user, our sessions can help you:<ul><li><strong>Navigate the Portal:</strong> Get comfortable with Sage's features.</li><li><strong>Request an Allocation at Sage:</strong> Get help with requesting resources and allocations on Sage.</li><li><strong>Build and Run AI Edge Applications:</strong> Develop and manage your AI applications.</li><li><strong>Ask Questions &amp; Get Unblocked:</strong> Receive assistance with any challenges you encounter.</li></ul><strong>Weekly Sessions:</strong><ul><li>Tuesdays: 11:00 AM - 12:00 PM CST</li><li>Thursdays: 3:00 PM - 4:00 PM CST</li></ul>To receive a Zoom link for a session, please make sure to <strong>register </strong><a href=\"https://docs.google.com/forms/d/e/1FAIpQLScHPrkWFr_CVTN2EQ9W0dXSlHtQ2JD6gs7P1Sf_MnQYApjgGA/viewform?usp=header\"><strong>here</strong></a>.If neither of these times work, please include your availability in the registration form and we will be happy to find a time that works for you. As always, please <a href=\"https://sagecontinuum.org/docs/contact-us\">Contact Us</a> if you have any questions. We look forward to hearing from you!",
      "contact": "support@waggle-edge.ai",
      "event_affiliation": "Community, nairr_pilot",
      "created": "2025-07-28T20:29:31Z",
      "changed": "2025-07-28T22:20:39Z",
      "event_type": "Office Hours",
      "location": "Virtual",
      "registration": "https://sagecontinuum.org/docs/events/office-hours",
      "skill_level": "Beginner, Intermediate, Advanced",
      "custom_event_tags": "ai, machine-learning, edge-computing, sensors, distributed-computing, gpu",
      "title": "Sage Office Hours",
      "field_video": "",
      "date": "2026-06-02T12:00:00Z",
      "date_1": "2026-06-02T13:00:00Z",
      "speakers": ""
    },
    {
      "id": "8502",
      "description": "Join our monthly community-hosted call<em>&nbsp;</em>to learn practical tips for using this powerful, web-based platform that gives you seamless access to HPC resources—no software needed.Happening the first Thursday of every month at 1 PM EDT, these sessions are ideal for both new and experienced users looking to streamline workflows and enhance research productivity.Register using the registration link to receive the Zoom details. Recordings of past sessions are available on the <a href=\"https://openondemand.org/resources#video-archive\">Open OnDemand website</a>.&nbsp;",
      "contact": "",
      "event_affiliation": "ACCESS Collaboration, nairr_pilot",
      "created": "2025-09-15T14:39:34Z",
      "changed": "2025-09-15T14:40:14Z",
      "event_type": "other",
      "location": "Zoom",
      "registration": "https://utah.zoom.us/meeting/register/tJYqfuqqrToqGtMMel3jTB6OGpi1hUWtFdmJ#/registration",
      "skill_level": "",
      "custom_event_tags": "open-ondemand",
      "title": "Open OnDemand Tips and Tricks Call",
      "field_video": "",
      "date": "2026-06-04T13:00:00Z",
      "date_1": "2026-06-04T14:00:00Z",
      "speakers": ""
    },
    {
      "id": "8149",
      "description": "<strong>Enhance Your Skills with Expert Guidance&nbsp;</strong>Join our informative Office Hours via Zoom to learn more about Sage. Whether you're new to Sage or an experienced user, our sessions can help you:<ul><li><strong>Navigate the Portal:</strong> Get comfortable with Sage's features.</li><li><strong>Request an Allocation at Sage:</strong> Get help with requesting resources and allocations on Sage.</li><li><strong>Build and Run AI Edge Applications:</strong> Develop and manage your AI applications.</li><li><strong>Ask Questions &amp; Get Unblocked:</strong> Receive assistance with any challenges you encounter.</li></ul><strong>Weekly Sessions:</strong><ul><li>Tuesdays: 11:00 AM - 12:00 PM CST</li><li>Thursdays: 3:00 PM - 4:00 PM CST</li></ul>To receive a Zoom link for a session, please make sure to <strong>register </strong><a href=\"https://docs.google.com/forms/d/e/1FAIpQLScHPrkWFr_CVTN2EQ9W0dXSlHtQ2JD6gs7P1Sf_MnQYApjgGA/viewform?usp=header\"><strong>here</strong></a>.If neither of these times work, please include your availability in the registration form and we will be happy to find a time that works for you. As always, please <a href=\"https://sagecontinuum.org/docs/contact-us\">Contact Us</a> if you have any questions. We look forward to hearing from you!",
      "contact": "support@waggle-edge.ai",
      "event_affiliation": "Community, nairr_pilot",
      "created": "2025-07-24T22:18:56Z",
      "changed": "2025-07-28T22:16:54Z",
      "event_type": "Office Hours",
      "location": "Virtual",
      "registration": "https://sagecontinuum.org/docs/events/office-hours",
      "skill_level": "Beginner, Intermediate, Advanced",
      "custom_event_tags": "ai, machine-learning, edge-computing, sensors, distributed-computing, gpu",
      "title": "Sage Office Hours",
      "field_video": "",
      "date": "2026-06-04T16:00:00Z",
      "date_1": "2026-06-04T17:00:00Z",
      "speakers": ""
    },
    {
      "id": "8214",
      "description": "<strong>Enhance Your Skills with Expert Guidance&nbsp;</strong>Join our informative Office Hours via Zoom to learn more about Sage. Whether you're new to Sage or an experienced user, our sessions can help you:<ul><li><strong>Navigate the Portal:</strong> Get comfortable with Sage's features.</li><li><strong>Request an Allocation at Sage:</strong> Get help with requesting resources and allocations on Sage.</li><li><strong>Build and Run AI Edge Applications:</strong> Develop and manage your AI applications.</li><li><strong>Ask Questions &amp; Get Unblocked:</strong> Receive assistance with any challenges you encounter.</li></ul><strong>Weekly Sessions:</strong><ul><li>Tuesdays: 11:00 AM - 12:00 PM CST</li><li>Thursdays: 3:00 PM - 4:00 PM CST</li></ul>To receive a Zoom link for a session, please make sure to <strong>register </strong><a href=\"https://docs.google.com/forms/d/e/1FAIpQLScHPrkWFr_CVTN2EQ9W0dXSlHtQ2JD6gs7P1Sf_MnQYApjgGA/viewform?usp=header\"><strong>here</strong></a>.If neither of these times work, please include your availability in the registration form and we will be happy to find a time that works for you. As always, please <a href=\"https://sagecontinuum.org/docs/contact-us\">Contact Us</a> if you have any questions. We look forward to hearing from you!",
      "contact": "support@waggle-edge.ai",
      "event_affiliation": "Community, nairr_pilot",
      "created": "2025-07-28T20:29:31Z",
      "changed": "2025-07-28T22:20:39Z",
      "event_type": "Office Hours",
      "location": "Virtual",
      "registration": "https://sagecontinuum.org/docs/events/office-hours",
      "skill_level": "Beginner, Intermediate, Advanced",
      "custom_event_tags": "ai, machine-learning, edge-computing, sensors, distributed-computing, gpu",
      "title": "Sage Office Hours",
      "field_video": "",
      "date": "2026-06-09T12:00:00Z",
      "date_1": "2026-06-09T13:00:00Z",
      "speakers": ""
    },
    {
      "id": "8150",
      "description": "<strong>Enhance Your Skills with Expert Guidance&nbsp;</strong>Join our informative Office Hours via Zoom to learn more about Sage. Whether you're new to Sage or an experienced user, our sessions can help you:<ul><li><strong>Navigate the Portal:</strong> Get comfortable with Sage's features.</li><li><strong>Request an Allocation at Sage:</strong> Get help with requesting resources and allocations on Sage.</li><li><strong>Build and Run AI Edge Applications:</strong> Develop and manage your AI applications.</li><li><strong>Ask Questions &amp; Get Unblocked:</strong> Receive assistance with any challenges you encounter.</li></ul><strong>Weekly Sessions:</strong><ul><li>Tuesdays: 11:00 AM - 12:00 PM CST</li><li>Thursdays: 3:00 PM - 4:00 PM CST</li></ul>To receive a Zoom link for a session, please make sure to <strong>register </strong><a href=\"https://docs.google.com/forms/d/e/1FAIpQLScHPrkWFr_CVTN2EQ9W0dXSlHtQ2JD6gs7P1Sf_MnQYApjgGA/viewform?usp=header\"><strong>here</strong></a>.If neither of these times work, please include your availability in the registration form and we will be happy to find a time that works for you. As always, please <a href=\"https://sagecontinuum.org/docs/contact-us\">Contact Us</a> if you have any questions. We look forward to hearing from you!",
      "contact": "support@waggle-edge.ai",
      "event_affiliation": "Community, nairr_pilot",
      "created": "2025-07-24T22:18:56Z",
      "changed": "2025-07-28T22:16:54Z",
      "event_type": "Office Hours",
      "location": "Virtual",
      "registration": "https://sagecontinuum.org/docs/events/office-hours",
      "skill_level": "Beginner, Intermediate, Advanced",
      "custom_event_tags": "ai, machine-learning, edge-computing, sensors, distributed-computing, gpu",
      "title": "Sage Office Hours",
      "field_video": "",
      "date": "2026-06-11T16:00:00Z",
      "date_1": "2026-06-11T17:00:00Z",
      "speakers": ""
    },
    {
      "id": "8215",
      "description": "<strong>Enhance Your Skills with Expert Guidance&nbsp;</strong>Join our informative Office Hours via Zoom to learn more about Sage. Whether you're new to Sage or an experienced user, our sessions can help you:<ul><li><strong>Navigate the Portal:</strong> Get comfortable with Sage's features.</li><li><strong>Request an Allocation at Sage:</strong> Get help with requesting resources and allocations on Sage.</li><li><strong>Build and Run AI Edge Applications:</strong> Develop and manage your AI applications.</li><li><strong>Ask Questions &amp; Get Unblocked:</strong> Receive assistance with any challenges you encounter.</li></ul><strong>Weekly Sessions:</strong><ul><li>Tuesdays: 11:00 AM - 12:00 PM CST</li><li>Thursdays: 3:00 PM - 4:00 PM CST</li></ul>To receive a Zoom link for a session, please make sure to <strong>register </strong><a href=\"https://docs.google.com/forms/d/e/1FAIpQLScHPrkWFr_CVTN2EQ9W0dXSlHtQ2JD6gs7P1Sf_MnQYApjgGA/viewform?usp=header\"><strong>here</strong></a>.If neither of these times work, please include your availability in the registration form and we will be happy to find a time that works for you. As always, please <a href=\"https://sagecontinuum.org/docs/contact-us\">Contact Us</a> if you have any questions. We look forward to hearing from you!",
      "contact": "support@waggle-edge.ai",
      "event_affiliation": "Community, nairr_pilot",
      "created": "2025-07-28T20:29:31Z",
      "changed": "2025-07-28T22:20:39Z",
      "event_type": "Office Hours",
      "location": "Virtual",
      "registration": "https://sagecontinuum.org/docs/events/office-hours",
      "skill_level": "Beginner, Intermediate, Advanced",
      "custom_event_tags": "ai, machine-learning, edge-computing, sensors, distributed-computing, gpu",
      "title": "Sage Office Hours",
      "field_video": "",
      "date": "2026-06-16T12:00:00Z",
      "date_1": "2026-06-16T13:00:00Z",
      "speakers": ""
    },
    {
      "id": "8151",
      "description": "<strong>Enhance Your Skills with Expert Guidance&nbsp;</strong>Join our informative Office Hours via Zoom to learn more about Sage. Whether you're new to Sage or an experienced user, our sessions can help you:<ul><li><strong>Navigate the Portal:</strong> Get comfortable with Sage's features.</li><li><strong>Request an Allocation at Sage:</strong> Get help with requesting resources and allocations on Sage.</li><li><strong>Build and Run AI Edge Applications:</strong> Develop and manage your AI applications.</li><li><strong>Ask Questions &amp; Get Unblocked:</strong> Receive assistance with any challenges you encounter.</li></ul><strong>Weekly Sessions:</strong><ul><li>Tuesdays: 11:00 AM - 12:00 PM CST</li><li>Thursdays: 3:00 PM - 4:00 PM CST</li></ul>To receive a Zoom link for a session, please make sure to <strong>register </strong><a href=\"https://docs.google.com/forms/d/e/1FAIpQLScHPrkWFr_CVTN2EQ9W0dXSlHtQ2JD6gs7P1Sf_MnQYApjgGA/viewform?usp=header\"><strong>here</strong></a>.If neither of these times work, please include your availability in the registration form and we will be happy to find a time that works for you. As always, please <a href=\"https://sagecontinuum.org/docs/contact-us\">Contact Us</a> if you have any questions. We look forward to hearing from you!",
      "contact": "support@waggle-edge.ai",
      "event_affiliation": "Community, nairr_pilot",
      "created": "2025-07-24T22:18:56Z",
      "changed": "2025-07-28T22:16:54Z",
      "event_type": "Office Hours",
      "location": "Virtual",
      "registration": "https://sagecontinuum.org/docs/events/office-hours",
      "skill_level": "Beginner, Intermediate, Advanced",
      "custom_event_tags": "ai, machine-learning, edge-computing, sensors, distributed-computing, gpu",
      "title": "Sage Office Hours",
      "field_video": "",
      "date": "2026-06-18T16:00:00Z",
      "date_1": "2026-06-18T17:00:00Z",
      "speakers": ""
    },
    {
      "id": "8216",
      "description": "<strong>Enhance Your Skills with Expert Guidance&nbsp;</strong>Join our informative Office Hours via Zoom to learn more about Sage. Whether you're new to Sage or an experienced user, our sessions can help you:<ul><li><strong>Navigate the Portal:</strong> Get comfortable with Sage's features.</li><li><strong>Request an Allocation at Sage:</strong> Get help with requesting resources and allocations on Sage.</li><li><strong>Build and Run AI Edge Applications:</strong> Develop and manage your AI applications.</li><li><strong>Ask Questions &amp; Get Unblocked:</strong> Receive assistance with any challenges you encounter.</li></ul><strong>Weekly Sessions:</strong><ul><li>Tuesdays: 11:00 AM - 12:00 PM CST</li><li>Thursdays: 3:00 PM - 4:00 PM CST</li></ul>To receive a Zoom link for a session, please make sure to <strong>register </strong><a href=\"https://docs.google.com/forms/d/e/1FAIpQLScHPrkWFr_CVTN2EQ9W0dXSlHtQ2JD6gs7P1Sf_MnQYApjgGA/viewform?usp=header\"><strong>here</strong></a>.If neither of these times work, please include your availability in the registration form and we will be happy to find a time that works for you. As always, please <a href=\"https://sagecontinuum.org/docs/contact-us\">Contact Us</a> if you have any questions. We look forward to hearing from you!",
      "contact": "support@waggle-edge.ai",
      "event_affiliation": "Community, nairr_pilot",
      "created": "2025-07-28T20:29:31Z",
      "changed": "2025-07-28T22:20:39Z",
      "event_type": "Office Hours",
      "location": "Virtual",
      "registration": "https://sagecontinuum.org/docs/events/office-hours",
      "skill_level": "Beginner, Intermediate, Advanced",
      "custom_event_tags": "ai, machine-learning, edge-computing, sensors, distributed-computing, gpu",
      "title": "Sage Office Hours",
      "field_video": "",
      "date": "2026-06-23T12:00:00Z",
      "date_1": "2026-06-23T13:00:00Z",
      "speakers": ""
    }
  ];
}