FROM ood:latest

ARG USER=ood
ARG UID=1000
ARG GID=1000

RUN dnf reinstall -y httpd-tools

RUN groupadd -g $GID $USER && \
    useradd -u $UID --create-home --gid $USER $USER && \
    /usr/bin/htpasswd -b -c /etc/httpd/.htpasswd $USER $USER

COPY lib/tasks/container_files/test/entrypoint.sh /entrypoint.sh

CMD [ "/entrypoint.sh" ]

