source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '6.0.4.1'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', group: :doc, require: false

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem 'climate_control', '~> 0.2'
  gem 'timecop', '~> 0.9'
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  # gem 'web-console', '~> 2.0'
end

# Extra third-party gems
gem 'dotenv-rails', '~> 2.1'
gem 'font-awesome-sass', '5.12.0'
gem 'redcarpet', '~> 3.3'
gem 'browser', '~> 2.2'
gem 'addressable', '~> 2.4'
gem 'bootstrap_form', '~> 4.0'
gem 'jquery-datatables-rails', '~> 3.4'
gem 'data-confirm-modal', '~> 1.2'
gem 'mocha', '~> 1.1', group: :test
gem 'autoprefixer-rails', '~> 10.2.5'
gem 'dotiw'
gem 'local_time', '~> 1.0.3'
gem 'turbolinks', '~> 5.2.0'

# OOD specific gems
gem 'ood_support', '~> 0.0.2'
gem 'ood_appkit', '~> 1.1',  git: 'https://github.com/osc/ood_appkit.git', branch: 'rails-6'
gem 'ood_core'
gem 'pbs', '~> 2.2.1'

# gems to include in ondemand-gems repo for status apps to use
gem "sinatra", require: false
gem "sinatra-contrib", require: false
gem "erubi", require: false
gem "dalli", require: false

gem 'webpacker', '~> 5.2', '>= 5.2.1'
gem 'zip_tricks', '~> 5.5'
