# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'dotenv', '~> 2.1'

group :development, :test do
  gem "rake"
  gem "rspec"
  gem "climate_control"
end
