name: Lint Random File

on:
  workflow_dispatch:
  schedule:
    # every 3 days
    - cron:  '0 2 */3 * *'

defaults:
  run:
    shell: bash

jobs:
  update-dependencies:
    strategy:
      fail-fast: false
    runs-on: 'ubuntu-latest'
    name: Lint Random File

    steps:
      - name: Checkout ${{ github.sha	}}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Ruby using Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.1"
          bundler: "2.1.4"
          bundler-cache: true

      - name: Lint a file
        run: bundle exec rake lint:random

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.OSC_ROBOT_GH_PUB_REPO_TOKEN }}
          commit-message: lint a random file
          committer: OSC ROBOT <osc.robot@gmail.com>
          author: osc-bot <osc.robot@gmail.com>
          delete-branch: true
          title: 'Lint a random file'
          push-to-fork: osc-bot/ondemand
          branch: osc-bot/random-linted-file
          body: |
            The result of linting a random file.

