name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release OnDemand
    steps:
      - name: Set version
        id: version
        run: echo ::set-output name=version::${GITHUB_REF#refs/*/v}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Ruby using Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.1"
          bundler: "2.1.4"
          bundler-cache: true
      - name: Generate tar.gz
        run: bundle exec rake package:tar
        env:
          VERSION: ${{ steps.version.outputs.version }}
          OOD_PACKAGING_DEBUG: 'true'
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload Release files
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: packaging/rpm/ondemand-${{ steps.version.outputs.version }}.tar.gz
          asset_name: ondemand-${{ steps.version.outputs.version }}.tar.gz
          asset_content_type: application/gzip
      - name: Upload to Zenodo
        uses: rseng/zenodo-release@0.0.17
        with:
          token: ${{ secrets.OSC_ROBOT_ZENODO_TOKEN }}
          version: ${{ steps.version.outputs.version }}
          zenodo_json: .zenodo.json
          archive: packaging/rpm/ondemand-${{ steps.version.outputs.version }}.tar.gz
          doi: '10.5281/zenodo.6323791'